"""Multi-language coding intelligence adapters."""

from khaos.coding.intelligence.context import (
    ContextBundle,
    ContextDocument,
    ContextEvidence,
    ContextEvidenceKind,
    ContextFreshness,
    ContextQueryReason,
    ContextRequest,
    ContextSourceKind,
    ContextSymbol,
    ContextTarget,
)
from khaos.coding.intelligence.models import ParseResult, SourceLocation, Symbol
from khaos.coding.intelligence.query import CodeQueryService
from khaos.coding.intelligence.registry import LanguageRegistry
from khaos.coding.intelligence.repository import (
    FreshnessPolicy,
    IntelligenceFreshness,
    MutationEvent,
    MutationType,
    RepoContextFile,
    RepoContextRequest,
    RepoContextResult,
    RepoContractError,
    RepoFile,
    RepoIntelligenceMetrics,
    RepoIntelligenceService,
    RepoIntelligenceIndexUnavailableError,
    RepoIntelligenceUnavailableError,
    RepoOverview,
    RepoQueryKind,
    RepoQueryRequest,
    RepoQueryResult,
    RepoRefreshReport,
    RepoRelation,
    RepoResourceLimits,
    RepoSymbol,
    RepoTextMatch,
    RepositoryIntelligenceService,
    RepositoryGeneration,
)

__all__ = [
    "CodeQueryService",
    "FreshnessPolicy",
    "ContextBundle",
    "ContextDocument",
    "ContextEvidence",
    "ContextEvidenceKind",
    "ContextFreshness",
    "ContextQueryReason",
    "ContextRequest",
    "ContextSourceKind",
    "ContextSymbol",
    "ContextTarget",
    "LanguageRegistry",
    "IntelligenceFreshness",
    "MutationEvent",
    "MutationType",
    "RepoContextFile",
    "RepoContextRequest",
    "RepoContextResult",
    "RepoContractError",
    "RepoFile",
    "RepoIntelligenceMetrics",
    "ParseResult",
    "RepoIntelligenceIndexUnavailableError",
    "RepoIntelligenceUnavailableError",
    "RepoOverview",
    "SourceLocation",
    "Symbol",
    "RepoIntelligenceService",
    "RepoQueryKind",
    "RepoQueryRequest",
    "RepoQueryResult",
    "RepoRefreshReport",
    "RepoRelation",
    "RepoResourceLimits",
    "RepoSymbol",
    "RepoTextMatch",
    "RepositoryIntelligenceService",
    "RepositoryGeneration",
]
