"""Public memory domain API.

Persistence and policy modules remain importable for composition and tests,
while the names historically imported from ``khaos.memory`` stay stable.
"""

from khaos.memory.adapters import AMLAdapterError, MemoryAMLAdapter, aml_add, aml_search
from khaos.memory.audit import MemoryAuditSinkAdapter, TrustKernelMemoryAuditSink
from khaos.memory.benchmarks import (
    BenchmarkCase,
    BenchmarkReport,
    BenchmarkRun,
    MemoryBenchmarkHarness,
    OnlineMemoryBenchmark,
    OnlineMemoryTask,
)
from khaos.memory.codegraph import (
    CodeGraphBuildReport,
    CodeGraphNode,
    CodeGraphService,
    repository_id_for_root,
)
from khaos.memory.conflict import ConflictDecision, ConflictResolver
from khaos.memory.conformance import (
    ProviderConformanceReport,
    ProviderConformanceSuite,
    run_provider_conformance,
)
from khaos.memory.core import (
    ContextAssembler,
    EntityRef,
    EvidenceRef,
    EvidenceResolution,
    ForgetResult,
    MemoryAuthority,
    MemoryBroker,
    MemoryCandidate,
    MemoryCapabilities,
    MemoryDecision,
    MemoryEvent,
    MemoryEventType,
    MemoryForgetRequest,
    MemoryForgetResult,
    MemoryHit,
    MemoryObjectIdentity,
    MemoryProvider,
    MemorySearchRequest,
    MemorySourceKind,
    MemoryStatus,
    MemoryType,
    MemoryWriteRequest,
    MemoryWriteResult,
    ProviderHealth,
    RelationCandidate,
    RuntimeMemoryContext,
    Sensitivity,
    SourceType,
    TrustHint,
    UsagePolicy,
    VerificationReceipt,
    candidate_digest,
    memory_digest,
)
from khaos.memory.decay import expired_memory_ids
from khaos.memory.events import MemoryEventBridge
from khaos.memory.extraction import (
    extract_candidates_from_event,
    extract_memories_from_messages,
    extract_memories_from_text,
)
from khaos.memory.maintenance import (
    ConsistencyReport,
    MaintenanceReport,
    MemoryMaintenanceService,
    RebuildReport,
)
from khaos.memory.manager import MemoryBudget, MemoryManager
from khaos.memory.models import Memory, MemoryConfidence, MemoryScope
from khaos.memory.observability import MemoryObservability, MetricSummary
from khaos.memory.ownership import MemoryOwner, MemoryVisibility
from khaos.memory.profiles import (
    CODING_PROFILE,
    PERSONAL_PROFILE,
    MemoryProfile,
    MemoryProfileError,
    MemoryProfileRegistry,
    MemoryProfileStore,
)
from khaos.memory.projection import (
    MemoryProjectionReducer,
    ProjectionRecord,
    stable_memory_id,
)
from khaos.memory.providers import (
    MemoryHttpProvider,
    MemoryProviderManager,
    MemoryProviderRegistry,
    NativeMemoryProvider,
    ProviderHandle,
    ProviderLifecycleError,
    ProviderLifecycleState,
    ProviderManifest,
    ProviderStatus,
    build_native_registry,
)
from khaos.memory.repository import MemoryRepository, SqliteMemoryRepository
from khaos.memory.retrieval import MemoryLayers, MemoryRetriever
from khaos.memory.retrieval_policy import (
    MemoryBundle,
    MemoryCurrentness,
    MemoryRetrievalNeed,
    MemoryRetrievalPolicy,
    MemoryRetrievalRequest,
    MemoryRetrievalScope,
    MemoryRetrievalService,
    MemoryRetrievalUnavailable,
    RepositoryStalenessPolicy,
    RetrievedMemory,
    classify_currentness,
    format_memory_bundle,
    memory_record_digest,
    provenance_for_hit,
    relevance_score,
    source_kind_for_hit,
)
from khaos.memory.runtime import MemoryHost, MemoryRuntime, MemoryRuntimeBinding
from khaos.memory.store import MemoryStore
from khaos.memory.transfer import MemoryTransferError, MemoryTransferService

__all__ = [
    "CODING_PROFILE",
    "PERSONAL_PROFILE",
    "AMLAdapterError",
    "BenchmarkCase",
    "BenchmarkReport",
    "BenchmarkRun",
    "CodeGraphBuildReport",
    "CodeGraphNode",
    "CodeGraphService",
    "ConflictDecision",
    "ConflictResolver",
    "ConsistencyReport",
    "ContextAssembler",
    "EntityRef",
    "EvidenceRef",
    "EvidenceResolution",
    "ForgetResult",
    "MaintenanceReport",
    "Memory",
    "MemoryAMLAdapter",
    "MemoryAuditSinkAdapter",
    "MemoryAuthority",
    "MemoryBenchmarkHarness",
    "MemoryBroker",
    "MemoryBudget",
    "MemoryCandidate",
    "MemoryCapabilities",
    "MemoryConfidence",
    "MemoryDecision",
    "MemoryEvent",
    "MemoryEventBridge",
    "MemoryEventType",
    "MemoryForgetRequest",
    "MemoryForgetResult",
    "MemoryHit",
    "MemoryHost",
    "MemoryHttpProvider",
    "MemoryLayers",
    "MemoryMaintenanceService",
    "MemoryManager",
    "MemoryObjectIdentity",
    "MemoryObservability",
    "MemoryOwner",
    "MemoryProfile",
    "MemoryProfileError",
    "MemoryProfileRegistry",
    "MemoryProfileStore",
    "MemoryProjectionReducer",
    "MemoryProvider",
    "MemoryProviderManager",
    "MemoryProviderRegistry",
    "MemoryRepository",
    "MemoryRetriever",
    "MemoryRuntime",
    "MemoryRuntimeBinding",
    "MemoryScope",
    "MemorySearchRequest",
    "MemorySourceKind",
    "MemoryStatus",
    "MemoryStore",
    "MemoryTransferError",
    "MemoryTransferService",
    "MemoryBundle",
    "MemoryCurrentness",
    "MemoryRetrievalNeed",
    "MemoryRetrievalPolicy",
    "MemoryRetrievalRequest",
    "MemoryRetrievalScope",
    "MemoryRetrievalService",
    "MemoryRetrievalUnavailable",
    "MemoryType",
    "MemoryVisibility",
    "MemoryWriteRequest",
    "MemoryWriteResult",
    "MetricSummary",
    "NativeMemoryProvider",
    "OnlineMemoryBenchmark",
    "OnlineMemoryTask",
    "ProjectionRecord",
    "ProviderConformanceReport",
    "ProviderConformanceSuite",
    "ProviderHandle",
    "ProviderHealth",
    "ProviderLifecycleError",
    "ProviderLifecycleState",
    "ProviderManifest",
    "ProviderStatus",
    "RebuildReport",
    "RelationCandidate",
    "RepositoryStalenessPolicy",
    "RuntimeMemoryContext",
    "RetrievedMemory",
    "Sensitivity",
    "SourceType",
    "SqliteMemoryRepository",
    "TrustHint",
    "TrustKernelMemoryAuditSink",
    "UsagePolicy",
    "VerificationReceipt",
    "aml_add",
    "aml_search",
    "build_native_registry",
    "candidate_digest",
    "expired_memory_ids",
    "extract_candidates_from_event",
    "extract_memories_from_messages",
    "extract_memories_from_text",
    "memory_digest",
    "memory_record_digest",
    "classify_currentness",
    "format_memory_bundle",
    "provenance_for_hit",
    "relevance_score",
    "source_kind_for_hit",
    "repository_id_for_root",
    "run_provider_conformance",
    "stable_memory_id",
]
