"""Tests for Phase 8.3 orchestrator tools.

The orchestrator tool handlers delegate to module-level globals (``_spawner`` /
``_runner``) injected by :func:`init_orchestrator`. Each test stubs those
globals via monkeypatch and asserts the handlers return the documented
``{"ok": ..., ...}`` contract — no real AgentLoop / DB is exercised here.
"""
from __future__ import annotations

import asyncio
import json
from unittest.mock import AsyncMock, MagicMock

import pytest

from khaos.tools import orchestrator_tools
from khaos.tools.orchestrator_tools import (
    collect_results,
    execute_plan,
    init_orchestrator,
    spawn_subagent,
    subagent_status,
)
from khaos.tools.registry import create_runtime_registry


# ─────────────────────────────── helpers ────────────────────────────────


def _fake_task(
    task_id: str = "t1",
    goal: str = "g",
    status: str = "completed",
    result: str | None = "ok",
    error: str | None = None,
):
    """Lightweight stand-in for SubAgentTask (duck-typed)."""
    return MagicMock(
        id=task_id,
        goal=goal,
        status=status,
        result=result,
        error=error,
    )


class _StubTask:
    """Mutable task stub — spawn() can flip its status to mimic real spawner."""

    def __init__(self, task_id="t1", goal="g", status="running",
                 result=None, error=None):
        self.id = task_id
        self.goal = goal
        self.status = status
        self.result = result
        self.error = error


def _make_spawner(spawn_side_effect=None, wait_all_return=None, wait_all_side_effect=None,
                  stats_value=None):
    """Build a fake SubAgentSpawner with AsyncMock methods."""
    spawner = MagicMock()
    spawner.spawn = AsyncMock(side_effect=spawn_side_effect)
    if wait_all_side_effect is not None:
        spawner.wait_all = AsyncMock(side_effect=wait_all_side_effect)
    else:
        spawner.wait_all = AsyncMock(return_value=wait_all_return or [])
    spawner.stats = MagicMock(return_value=stats_value or {
        "active": 0, "total": 0, "completed": 0, "failed": 0, "pending": 0,
    })
    return spawner


@pytest.fixture
def reset_globals():
    """Ensure module globals are cleared after each test (test isolation)."""
    yield
    orchestrator_tools._spawner = None
    orchestrator_tools._runner = None


# ──────────────────────────── init_orchestrator ─────────────────────────


def test_init_orchestrator_injects_globals(reset_globals):
    spawner = MagicMock()
    runner = MagicMock()
    init_orchestrator(spawner, runner)

    assert orchestrator_tools._spawner is spawner
    assert orchestrator_tools._runner is runner


def test_init_orchestrator_overwrites_previous(reset_globals):
    init_orchestrator(MagicMock(), MagicMock())
    spawner2, runner2 = MagicMock(), MagicMock()
    init_orchestrator(spawner2, runner2)

    assert orchestrator_tools._spawner is spawner2
    assert orchestrator_tools._runner is runner2


# ───────────────────────────── spawn_subagent ──────────────────────────


async def test_spawn_subagent_success(reset_globals):
    spawned = _StubTask(task_id="t42", status="running")
    spawner = _make_spawner(spawn_side_effect=lambda _task: spawned)
    init_orchestrator(spawner, MagicMock())

    result = await spawn_subagent(
        goal="write tests", context="ctx", tools=["read_file"],
        principal_id="user1",
    )

    assert result["ok"] is True
    assert result["task_id"] == "t42"
    assert result["status"] == "running"
    # spawn was called with a SubAgentTask whose fields were derived from args
    task_arg = spawner.spawn.call_args.args[0]
    assert task_arg.goal == "write tests"
    assert task_arg.context == "ctx"
    assert task_arg.tools == ["read_file"]
    assert task_arg.id == ""  # id auto-generated by spawner


async def test_spawn_subagent_defaults(reset_globals):
    spawned = _StubTask(task_id="t1")
    spawner = _make_spawner(spawn_side_effect=lambda _task: spawned)
    init_orchestrator(spawner, MagicMock())

    result = await spawn_subagent(goal="only goal", principal_id="user1")

    assert result["ok"] is True
    task_arg = spawner.spawn.call_args.args[0]
    assert task_arg.context == ""
    assert task_arg.tools == []
    assert task_arg.timeout == 300


async def test_spawn_subagent_not_initialized(reset_globals):
    orchestrator_tools._spawner = None
    result = await spawn_subagent(goal="x")
    assert result == {"ok": False, "error": "Orchestrator not initialized"}


async def test_spawn_subagent_handles_exception(reset_globals):
    spawner = _make_spawner(spawn_side_effect=RuntimeError("concurrency full"))
    init_orchestrator(spawner, MagicMock())

    result = await spawn_subagent(goal="x", principal_id="user1")
    assert result["ok"] is False
    assert "concurrency full" in result["error"]


async def test_spawn_subagent_handles_subagent_limit_error(reset_globals):
    from khaos.exceptions import SubAgentLimitError

    spawner = _make_spawner(spawn_side_effect=SubAgentLimitError("depth exceeded"))
    init_orchestrator(spawner, MagicMock())

    result = await spawn_subagent(goal="x", principal_id="user1")
    assert result["ok"] is False
    assert "depth exceeded" in result["error"]


# ───────────────────────────── collect_results ─────────────────────────


async def test_collect_results_success(reset_globals):
    tasks = [
        _StubTask("t1", "goal 1", "completed", result="r1"),
        _StubTask("t2", "goal 2", "failed", result=None, error="boom"),
    ]
    spawner = _make_spawner(wait_all_return=tasks)
    init_orchestrator(spawner, MagicMock())

    result = await collect_results(principal_id="user1")

    assert result["ok"] is True
    assert result["total"] == 2
    assert result["completed"] == 1
    assert result["failed"] == 1
    assert result["results"][0] == {
        "task_id": "t1", "goal": "goal 1", "status": "completed",
        "result": "r1", "error": None,
    }
    assert result["results"][1]["status"] == "failed"
    assert result["results"][1]["error"] == "boom"


async def test_collect_results_empty(reset_globals):
    spawner = _make_spawner(wait_all_return=[])
    init_orchestrator(spawner, MagicMock())

    result = await collect_results(principal_id="user1")
    assert result["ok"] is True
    assert result["total"] == 0
    assert result["completed"] == 0
    assert result["failed"] == 0
    assert result["results"] == []


async def test_collect_results_not_initialized(reset_globals):
    orchestrator_tools._spawner = None
    result = await collect_results()
    assert result == {"ok": False, "error": "Orchestrator not initialized"}


async def test_collect_results_handles_timeout(reset_globals):
    spawner = _make_spawner(wait_all_side_effect=asyncio.TimeoutError())
    init_orchestrator(spawner, MagicMock())

    result = await collect_results(principal_id="user1")
    assert result["ok"] is False
    assert "error" in result


# ────────────────────────────── execute_plan ───────────────────────────


async def test_execute_plan_success(reset_globals):
    """execute_plan drives real SubAgentTask objects through the spawner.

    The mock spawn flips each task to ``completed`` (mimicking the real
    spawner's _run_task), and the planner returns those same task objects.
    """
    async def completing_spawn(task):
        task.status = "completed"
        task.result = f"done:{task.goal}"
        return task

    spawner = _make_spawner(spawn_side_effect=completing_spawn, wait_all_return=[])
    init_orchestrator(spawner, MagicMock())

    plan_json = json.dumps({
        "description": "parallel",
        "tasks": [{"goal": "a"}, {"goal": "b"}],
    })
    result = await execute_plan(plan_json, principal_id="user1")

    assert result["ok"] is True
    assert "plan_id" in result
    assert result["total"] == 2
    assert result["completed"] == 2
    assert result["failed"] == 0
    goals = sorted(r["goal"] for r in result["results"])
    assert goals == ["a", "b"]


async def test_execute_plan_invalid_json(reset_globals):
    init_orchestrator(_make_spawner(), MagicMock())

    result = await execute_plan("not valid json", principal_id="user1")
    assert result["ok"] is False
    assert "error" in result


async def test_execute_plan_empty_object_json(reset_globals):
    """A valid JSON object with no tasks parses but yields zero results."""
    init_orchestrator(_make_spawner(), MagicMock())

    result = await execute_plan('{"tasks": []}', principal_id="user1")
    assert result["ok"] is True
    assert result["total"] == 0


async def test_execute_plan_not_initialized(reset_globals):
    orchestrator_tools._spawner = None
    result = await execute_plan('{"tasks":[]}')
    assert result == {"ok": False, "error": "Orchestrator not initialized"}


async def test_execute_plan_reports_failures(reset_globals):
    """First task fails → second task (depends on first) is marked skipped by planner."""
    async def failing_then_skip(task):
        if task.goal == "a":
            task.status = "failed"
            task.error = "boom"
        # task_2 should be skipped by the planner BEFORE spawn is called,
        # so we don't need to handle it here.
        return task

    spawner = _make_spawner(spawn_side_effect=failing_then_skip, wait_all_return=[])
    init_orchestrator(spawner, MagicMock())

    plan_json = json.dumps({
        "tasks": [{"goal": "a"}, {"goal": "b"}],
        "dependencies": {"task_2": ["task_1"]},
    })
    result = await execute_plan(plan_json, principal_id="user1")

    assert result["ok"] is True
    assert result["failed"] == 1  # only the first task counts as failed
    statuses = {r["status"] for r in result["results"]}
    assert "skipped" in statuses  # task_2 was skipped
    assert "failed" in statuses


# ───────────────────────────── subagent_status ─────────────────────────


async def test_subagent_status_returns_stats(reset_globals):
    stats = {"active": 2, "total": 5, "completed": 2, "failed": 1, "pending": 0}
    spawner = _make_spawner(stats_value=stats)
    init_orchestrator(spawner, MagicMock())

    result = await subagent_status(principal_id="user1")
    assert result == {"ok": True, "stats": stats}


async def test_subagent_status_not_initialized(reset_globals):
    orchestrator_tools._spawner = None
    result = await subagent_status()
    assert result == {"ok": False, "error": "Orchestrator not initialized"}


# ──────────────────────────── registry wiring ──────────────────────────


def test_runtime_registry_wires_orchestrator_handlers():
    """create_runtime_registry must attach the 4 orchestrator handlers."""
    registry = create_runtime_registry()
    for name in ("spawn_subagent", "collect_results", "execute_plan", "subagent_status"):
        tool = registry.get(name)
        assert tool.handler is not None, f"{name} handler not wired"
        assert callable(tool.handler)


def test_orchestrator_tools_available_in_office_and_coding():
    registry = create_runtime_registry()
    office_names = {t.name for t in registry.list_by_mode("office")}
    coding_names = {t.name for t in registry.list_by_mode("coding")}
    for name in ("spawn_subagent", "collect_results", "execute_plan", "subagent_status"):
        assert name in office_names, f"{name} not available in office mode"
        assert name in coding_names, f"{name} not available in coding mode"


def test_orchestrator_permission_levels():
    registry = create_runtime_registry()
    assert registry.get("spawn_subagent").permission_level == "write"
    assert registry.get("collect_results").permission_level == "read"
    assert registry.get("execute_plan").permission_level == "write"
    assert registry.get("subagent_status").permission_level == "read"


# ─────────── MEDIUM (batch 3.1.8): capability + principal wiring ──────────


def test_orchestrator_tools_declare_subagent_spawn_capability():
    """MEDIUM (batch 3.1.8): the four orchestrator tools MUST declare
    the ``subagent.spawn`` capability so ``ToolInvocationBroker.invoke``
    injects ``principal_id`` into the handler kwargs.  Without a
    declared capability the broker treats them as no-capability tools
    and the handlers receive ``principal_id=""`` even when the caller
    is authenticated — the spawner returns an empty list for an empty
    principal, so ``collect_results`` / ``subagent_status`` can never
    observe tasks spawned via ``spawn_subagent``.
    """
    registry = create_runtime_registry()
    for name in (
        "spawn_subagent",
        "collect_results",
        "execute_plan",
        "subagent_status",
    ):
        tool = registry.get(name)
        cap_names = {c.name for c in tool.capabilities}
        assert "subagent.spawn" in cap_names, (
            f"{name} must declare subagent.spawn capability; got {cap_names}"
        )


async def test_broker_injects_principal_id_for_subagent_spawn(reset_globals):
    """MEDIUM (batch 3.1.8): ``ToolInvocationBroker.invoke`` MUST
    inject ``principal_id`` from the context dict when the tool
    declares the ``subagent.spawn`` capability.  This is the glue
    between the authenticated caller and the spawner's per-principal
    filtering — without it, the handler always receives an empty
    principal and can never observe its own tasks.
    """
    from khaos.tools.registry import ToolInvocationBroker

    captured: dict = {}

    async def fake_handler(*, principal_id: str = "", **_kwargs):
        captured["principal_id"] = principal_id
        return {"ok": True, "principal_id": principal_id}

    registry = create_runtime_registry()
    # Replace the spawn_subagent handler with a spy that records the
    # injected principal_id.  The tool definition (with its
    # ``subagent.spawn`` capability) is unchanged.
    registry.get("spawn_subagent").handler = fake_handler

    broker = ToolInvocationBroker(registry)
    result = await broker.invoke(
        "spawn_subagent",
        mode="office",
        context={"principal_id": "user1"},
        goal="x",
    )

    assert captured["principal_id"] == "user1", (
        f"broker did not inject principal_id; got {captured}"
    )
    assert result["principal_id"] == "user1"


async def test_orchestrator_tools_principal_isolation_integration(tmp_path):
    """MEDIUM (batch 3.1.8) acceptance #5: end-to-end integration test
    using a REAL SubAgentSpawner + SQLite.  ``spawn_subagent`` stamps
    the caller's principal on the task; ``collect_results`` /
    ``subagent_status`` filter on it.  A different principal sees
    nothing (defense-in-depth against cross-principal leakage).
    """
    from khaos.db import Database
    from khaos.subagents.spawner import SubAgentConfig, SubAgentSpawner
    from khaos.tools.registry import ToolInvocationBroker

    async def quick_runner(task):
        return f"done:{task.goal}"

    db = Database(tmp_path / "khaos.db")
    await db.connect()
    await db.run_migrations()
    spawner = SubAgentSpawner(
        SubAgentConfig(max_concurrent=3), db, runner=quick_runner,
    )
    init_orchestrator(spawner, MagicMock())
    try:
        registry = create_runtime_registry()
        broker = ToolInvocationBroker(registry)

        # Spawn as user1 via the broker — exercises the full
        # capability-gated principal_id injection path.
        ctx_user1 = {"principal_id": "user1"}
        result = await broker.invoke(
            "spawn_subagent",
            mode="office",
            context=ctx_user1,
            goal="hello",
        )
        assert result["ok"] is True
        assert result["principal_id"] == "user1"
        task_id = result["task_id"]

        # Wait for the spawned task to finish so collect/status see
        # the terminal state.
        await spawner.wait_all(principal_id="user1")

        # Collect as user1 — should see the one completed task.
        collect = await broker.invoke(
            "collect_results",
            mode="office",
            context=ctx_user1,
        )
        assert collect["ok"] is True
        assert collect["total"] == 1
        assert collect["completed"] == 1
        assert collect["results"][0]["task_id"] == task_id

        # Status as user1 — should see the one completed task.
        status = await broker.invoke(
            "subagent_status",
            mode="office",
            context=ctx_user1,
        )
        assert status["ok"] is True
        assert status["stats"]["total"] == 1
        assert status["stats"]["completed"] == 1
        assert status["stats"]["active"] == 0

        # Status as user2 — should see ZERO tasks (per-principal
        # isolation; the spawner returns empty for a different
        # principal).
        ctx_user2 = {"principal_id": "user2"}
        status2 = await broker.invoke(
            "subagent_status",
            mode="office",
            context=ctx_user2,
        )
        assert status2["ok"] is True
        assert status2["stats"]["total"] == 0
        assert status2["stats"]["completed"] == 0
    finally:
        orchestrator_tools._spawner = None
        orchestrator_tools._runner = None
        await db.close()


async def test_spawn_subagent_returns_real_failure_when_spawner_rejects(
    tmp_path, reset_globals,
):
    """MEDIUM (batch 3.1.8) acceptance #4: when the spawner rejects
    spawn (here: shutdown already begun), the orchestrator tool MUST
    return the real failure — NOT the legacy hard-coded
    ``{"ok": True, "status": "running"}``.

    Previously the handler ignored the spawner's result and always
    returned ``status="running"``, hiding every rejection
    (concurrency full / depth exceeded / shutting down) behind a
    false success.
    """
    from khaos.db import Database
    from khaos.subagents.spawner import SubAgentConfig, SubAgentSpawner

    db = Database(tmp_path / "khaos.db")
    await db.connect()
    await db.run_migrations()
    spawner = SubAgentSpawner(SubAgentConfig(max_concurrent=3), db)
    init_orchestrator(spawner, MagicMock())
    try:
        # Trigger shutdown — every subsequent spawn is rejected with
        # SubAgentLimitError("subagent spawner is shutting down").
        await spawner.shutdown(timeout=1.0)

        result = await spawn_subagent(goal="x", principal_id="user1")

        # Real failure surfaced — NOT the hard-coded "running".
        assert result["ok"] is False, (
            f"expected ok=False (spawner is shutting down), got: {result}"
        )
        assert "shutting down" in result["error"], (
            f"expected 'shutting down' in error, got: {result}"
        )
        # Defense-in-depth: status must never be the legacy "running".
        assert result.get("status") != "running"
    finally:
        orchestrator_tools._spawner = None
        orchestrator_tools._runner = None
        await db.close()


async def test_build_subagent_service_wires_init_orchestrator(tmp_path):
    """MEDIUM (batch 3.1.8) acceptance #6: production startup MUST
    call ``init_orchestrator`` so the four orchestrator tool handlers
    no longer return ``"Orchestrator not initialized"``.

    ``_build_subagent_service`` constructs the real ``SubAgentSpawner``
    + ``SubAgentRunner`` but previously did NOT call
    ``init_orchestrator`` — so the orchestrator tool module-level
    globals (``_spawner`` / ``_runner``) stayed ``None`` and every
    handler returned ``{"ok": False, "error": "Orchestrator not
    initialized"}`` in production.  This test pins the wiring by
    monkeypatching ``init_orchestrator`` and asserting the call.
    """
    import khaos.grpc_server as grpc_module
    from khaos.db import Database
    from khaos.tools import orchestrator_tools as orch_module

    db = Database(tmp_path / "khaos.db")
    await db.connect()
    await db.run_migrations()
    (tmp_path / "prompts").mkdir()
    (tmp_path / "prompts" / "office.md").write_text("office", encoding="utf-8")
    (tmp_path / "prompts" / "coding.md").write_text("coding", encoding="utf-8")
    (tmp_path / "config.yaml").write_text(
        "providers: {}\nmodels: {}\n", encoding="utf-8",
    )

    captured: list[tuple] = []

    real_init = orch_module.init_orchestrator

    def spy_init(spawner, runner):
        captured.append((spawner, runner))
        # Delegate to the real init so the rest of _build_subagent_service
        # sees a consistent module state.
        real_init(spawner, runner)

    original_init = grpc_module.__dict__.get("init_orchestrator")
    # _build_subagent_service imports init_orchestrator lazily from
    # khaos.tools.orchestrator_tools, so patch it on the source module.
    orch_module.init_orchestrator = spy_init
    try:
        await grpc_module._build_subagent_service(
            db,
            project_root=tmp_path,
            config_path=tmp_path / "config.yaml",
        )
        assert captured, (
            "_build_subagent_service did not call init_orchestrator; "
            "the 4 orchestrator tools would return 'Orchestrator not "
            "initialized' in production"
        )
        # The spawner passed to init_orchestrator is the real one
        # constructed inside _build_subagent_service.
        spawner_arg, runner_arg = captured[0]
        from khaos.subagents.spawner import SubAgentSpawner
        from khaos.subagents.runner import SubAgentRunner
        assert isinstance(spawner_arg, SubAgentSpawner)
        assert isinstance(runner_arg, SubAgentRunner)
        # And the module globals are now wired.
        assert orch_module._spawner is spawner_arg
        assert orch_module._runner is runner_arg
    finally:
        orch_module.init_orchestrator = real_init
        orch_module._spawner = None
        orch_module._runner = None
        await db.close()


async def test_build_subagent_service_orchestrator_tools_not_initialized_after(
    tmp_path,
):
    """MEDIUM (batch 3.1.8) acceptance #6 (behavioural mirror): after
    ``_build_subagent_service`` runs, calling ``spawn_subagent``
    directly MUST NOT return ``"Orchestrator not initialized"`` —
    i.e. the production init wired the globals.
    """
    import khaos.grpc_server as grpc_module
    from khaos.db import Database
    from khaos.tools import orchestrator_tools as orch_module

    db = Database(tmp_path / "khaos.db")
    await db.connect()
    await db.run_migrations()
    (tmp_path / "prompts").mkdir()
    (tmp_path / "prompts" / "office.md").write_text("office", encoding="utf-8")
    (tmp_path / "prompts" / "coding.md").write_text("coding", encoding="utf-8")
    (tmp_path / "config.yaml").write_text(
        "providers: {}\nmodels: {}\n", encoding="utf-8",
    )
    try:
        await grpc_module._build_subagent_service(
            db,
            project_root=tmp_path,
            config_path=tmp_path / "config.yaml",
        )
        # The handler should no longer short-circuit with "Orchestrator
        # not initialized" — it should reach the spawner and either
        # succeed or fail with a real spawner error.
        result = await spawn_subagent(goal="x", principal_id="user1")
        assert result.get("error") != "Orchestrator not initialized", (
            f"orchestrator tools still not initialized in production: {result}"
        )
    finally:
        orch_module._spawner = None
        orch_module._runner = None
        await db.close()


# ───────── MEDIUM (batch 3.1.9): shutdown-race ok=false + principal required ─────────


async def test_spawn_subagent_shutdown_race_returns_ok_false(reset_globals) -> None:
    """MEDIUM-1 (batch 3.1.9) acceptance #5: when the spawner returns
    a task with a terminal failure status (``failed`` / ``cancelled``)
    — e.g. the spawn lost a shutdown race and the task was aborted —
    ``spawn_subagent`` MUST return ``ok=false`` with the task's error,
    NOT ``ok=true, status="failed"``.

    Previously the handler hard-coded ``ok=true`` for every non-exception
    return, so a shutdown-race abort produced:
        ``{"ok": true, "status": "failed", ...}``
    which contradicts the ``ok`` flag's meaning and breaks callers that
    branch on ``ok``.  The RPC ``SubAgentService`` already returns
    ``ok=false`` for terminal failures; the tool path now matches.
    """
    # Simulate the spawner's shutdown-race path: it returns the task
    # normally (no exception) but with status="failed" and
    # error="cancelled" — exactly what happens when shutdown begins
    # during the DB work and the reservation is aborted.
    aborted_task = _StubTask(
        task_id="t-aborted",
        status="failed",
        error="cancelled",
    )
    spawner = _make_spawner(spawn_side_effect=lambda _task: aborted_task)
    init_orchestrator(spawner, MagicMock())

    result = await spawn_subagent(goal="x", principal_id="user1")

    assert result["ok"] is False, (
        f"expected ok=false (status=failed), got ok={result['ok']}, "
        f"full result: {result}"
    )
    assert result["status"] == "failed", (
        f"expected status=failed, got: {result.get('status')}"
    )
    assert result["error"] == "cancelled", (
        f"expected error='cancelled', got: {result.get('error')}"
    )
    assert result["task_id"] == "t-aborted"


async def test_spawn_subagent_cancelled_status_also_returns_ok_false(
    reset_globals,
) -> None:
    """MEDIUM-1 (batch 3.1.9): ``cancelled`` is also a terminal failure
    status — verify the handler returns ``ok=false`` for it too (not
    just ``failed``).
    """
    cancelled_task = _StubTask(
        task_id="t-cancelled",
        status="cancelled",
        error="shutdown",
    )
    spawner = _make_spawner(spawn_side_effect=lambda _task: cancelled_task)
    init_orchestrator(spawner, MagicMock())

    result = await spawn_subagent(goal="x", principal_id="user1")

    assert result["ok"] is False
    assert result["status"] == "cancelled"
    assert result["error"] == "shutdown"


@pytest.mark.parametrize(
    "handler_name,handler,kwargs",
    [
        ("spawn_subagent", spawn_subagent, {"goal": "x"}),
        ("collect_results", collect_results, {}),
        ("execute_plan", execute_plan, {"plan_json": '{"tasks": []}'}),
        ("subagent_status", subagent_status, {}),
    ],
)
async def test_orchestrator_tools_refuse_empty_principal(
    handler_name, handler, kwargs, reset_globals,
) -> None:
    """MEDIUM-2 (batch 3.1.9) acceptance #6: all four orchestrator
    handlers MUST refuse empty ``principal_id`` instead of falling
    back to a shared pseudo-principal (``local-uid:orchestrator``).

    The fallback was fail-open: any handler invoked without an
    authenticated principal (e.g. a misconfigured tool context) would
    silently land all tasks under a shared pseudo-principal, bypassing
    the spawner's "empty principal → empty result" defense.  The RPC
    path already requires a principal; the tool path now matches.
    """
    init_orchestrator(_make_spawner(), MagicMock())

    # Empty principal_id (the default) — must be refused.
    result = await handler(**kwargs)
    assert result["ok"] is False, (
        f"{handler_name}: expected ok=false for empty principal_id, "
        f"got: {result}"
    )
    assert result["error"] == "principal_id is required", (
        f"{handler_name}: expected 'principal_id is required' error, "
        f"got: {result.get('error')}"
    )

    # Also explicitly empty string.
    result = await handler(principal_id="", **kwargs)
    assert result["ok"] is False
    assert result["error"] == "principal_id is required"
