"""Tests for Phase 8.3 orchestrator tools.

The orchestrator tool handlers delegate to module-level globals (``_spawner`` /
``_runner``) injected by :func:`init_orchestrator`. Each test stubs those
globals via monkeypatch and asserts the handlers return the documented
``{"ok": ..., ...}`` contract — no real AgentLoop / DB is exercised here.
"""
from __future__ import annotations

import asyncio
import json
from unittest.mock import AsyncMock, MagicMock

import pytest

from khaos.tools import orchestrator_tools
from khaos.tools.orchestrator_tools import (
    collect_results,
    execute_plan,
    init_orchestrator,
    spawn_subagent,
    subagent_status,
)
from khaos.tools.registry import create_runtime_registry


# ─────────────────────────────── helpers ────────────────────────────────


def _fake_task(
    task_id: str = "t1",
    goal: str = "g",
    status: str = "completed",
    result: str | None = "ok",
    error: str | None = None,
):
    """Lightweight stand-in for SubAgentTask (duck-typed)."""
    return MagicMock(
        id=task_id,
        goal=goal,
        status=status,
        result=result,
        error=error,
    )


class _StubTask:
    """Mutable task stub — spawn() can flip its status to mimic real spawner."""

    def __init__(self, task_id="t1", goal="g", status="running",
                 result=None, error=None):
        self.id = task_id
        self.goal = goal
        self.status = status
        self.result = result
        self.error = error


def _make_spawner(spawn_side_effect=None, wait_all_return=None, wait_all_side_effect=None,
                  stats_value=None):
    """Build a fake SubAgentSpawner with AsyncMock methods."""
    spawner = MagicMock()
    spawner.spawn = AsyncMock(side_effect=spawn_side_effect)
    if wait_all_side_effect is not None:
        spawner.wait_all = AsyncMock(side_effect=wait_all_side_effect)
    else:
        spawner.wait_all = AsyncMock(return_value=wait_all_return or [])
    spawner.stats = MagicMock(return_value=stats_value or {
        "active": 0, "total": 0, "completed": 0, "failed": 0, "pending": 0,
    })
    return spawner


@pytest.fixture
def reset_globals():
    """Ensure module globals are cleared after each test (test isolation)."""
    yield
    orchestrator_tools._spawner = None
    orchestrator_tools._runner = None


# ──────────────────────────── init_orchestrator ─────────────────────────


def test_init_orchestrator_injects_globals(reset_globals):
    spawner = MagicMock()
    runner = MagicMock()
    init_orchestrator(spawner, runner)

    assert orchestrator_tools._spawner is spawner
    assert orchestrator_tools._runner is runner


def test_init_orchestrator_overwrites_previous(reset_globals):
    init_orchestrator(MagicMock(), MagicMock())
    spawner2, runner2 = MagicMock(), MagicMock()
    init_orchestrator(spawner2, runner2)

    assert orchestrator_tools._spawner is spawner2
    assert orchestrator_tools._runner is runner2


# ───────────────────────────── spawn_subagent ──────────────────────────


async def test_spawn_subagent_success(reset_globals):
    spawned = _StubTask(task_id="t42", status="running")
    spawner = _make_spawner(spawn_side_effect=lambda _task: spawned)
    init_orchestrator(spawner, MagicMock())

    result = await spawn_subagent(goal="write tests", context="ctx", tools=["read_file"])

    assert result["ok"] is True
    assert result["task_id"] == "t42"
    assert result["status"] == "running"
    # spawn was called with a SubAgentTask whose fields were derived from args
    task_arg = spawner.spawn.call_args.args[0]
    assert task_arg.goal == "write tests"
    assert task_arg.context == "ctx"
    assert task_arg.tools == ["read_file"]
    assert task_arg.id == ""  # id auto-generated by spawner


async def test_spawn_subagent_defaults(reset_globals):
    spawned = _StubTask(task_id="t1")
    spawner = _make_spawner(spawn_side_effect=lambda _task: spawned)
    init_orchestrator(spawner, MagicMock())

    result = await spawn_subagent(goal="only goal")

    assert result["ok"] is True
    task_arg = spawner.spawn.call_args.args[0]
    assert task_arg.context == ""
    assert task_arg.tools == []
    assert task_arg.timeout == 300


async def test_spawn_subagent_not_initialized(reset_globals):
    orchestrator_tools._spawner = None
    result = await spawn_subagent(goal="x")
    assert result == {"ok": False, "error": "Orchestrator not initialized"}


async def test_spawn_subagent_handles_exception(reset_globals):
    spawner = _make_spawner(spawn_side_effect=RuntimeError("concurrency full"))
    init_orchestrator(spawner, MagicMock())

    result = await spawn_subagent(goal="x")
    assert result["ok"] is False
    assert "concurrency full" in result["error"]


async def test_spawn_subagent_handles_subagent_limit_error(reset_globals):
    from khaos.exceptions import SubAgentLimitError

    spawner = _make_spawner(spawn_side_effect=SubAgentLimitError("depth exceeded"))
    init_orchestrator(spawner, MagicMock())

    result = await spawn_subagent(goal="x")
    assert result["ok"] is False
    assert "depth exceeded" in result["error"]


# ───────────────────────────── collect_results ─────────────────────────


async def test_collect_results_success(reset_globals):
    tasks = [
        _StubTask("t1", "goal 1", "completed", result="r1"),
        _StubTask("t2", "goal 2", "failed", result=None, error="boom"),
    ]
    spawner = _make_spawner(wait_all_return=tasks)
    init_orchestrator(spawner, MagicMock())

    result = await collect_results()

    assert result["ok"] is True
    assert result["total"] == 2
    assert result["completed"] == 1
    assert result["failed"] == 1
    assert result["results"][0] == {
        "task_id": "t1", "goal": "goal 1", "status": "completed",
        "result": "r1", "error": None,
    }
    assert result["results"][1]["status"] == "failed"
    assert result["results"][1]["error"] == "boom"


async def test_collect_results_empty(reset_globals):
    spawner = _make_spawner(wait_all_return=[])
    init_orchestrator(spawner, MagicMock())

    result = await collect_results()
    assert result["ok"] is True
    assert result["total"] == 0
    assert result["completed"] == 0
    assert result["failed"] == 0
    assert result["results"] == []


async def test_collect_results_not_initialized(reset_globals):
    orchestrator_tools._spawner = None
    result = await collect_results()
    assert result == {"ok": False, "error": "Orchestrator not initialized"}


async def test_collect_results_handles_timeout(reset_globals):
    spawner = _make_spawner(wait_all_side_effect=asyncio.TimeoutError())
    init_orchestrator(spawner, MagicMock())

    result = await collect_results()
    assert result["ok"] is False
    assert "error" in result


# ────────────────────────────── execute_plan ───────────────────────────


async def test_execute_plan_success(reset_globals):
    """execute_plan drives real SubAgentTask objects through the spawner.

    The mock spawn flips each task to ``completed`` (mimicking the real
    spawner's _run_task), and the planner returns those same task objects.
    """
    async def completing_spawn(task):
        task.status = "completed"
        task.result = f"done:{task.goal}"
        return task

    spawner = _make_spawner(spawn_side_effect=completing_spawn, wait_all_return=[])
    init_orchestrator(spawner, MagicMock())

    plan_json = json.dumps({
        "description": "parallel",
        "tasks": [{"goal": "a"}, {"goal": "b"}],
    })
    result = await execute_plan(plan_json)

    assert result["ok"] is True
    assert "plan_id" in result
    assert result["total"] == 2
    assert result["completed"] == 2
    assert result["failed"] == 0
    goals = sorted(r["goal"] for r in result["results"])
    assert goals == ["a", "b"]


async def test_execute_plan_invalid_json(reset_globals):
    init_orchestrator(_make_spawner(), MagicMock())

    result = await execute_plan("not valid json")
    assert result["ok"] is False
    assert "error" in result


async def test_execute_plan_empty_object_json(reset_globals):
    """A valid JSON object with no tasks parses but yields zero results."""
    init_orchestrator(_make_spawner(), MagicMock())

    result = await execute_plan('{"tasks": []}')
    assert result["ok"] is True
    assert result["total"] == 0


async def test_execute_plan_not_initialized(reset_globals):
    orchestrator_tools._spawner = None
    result = await execute_plan('{"tasks":[]}')
    assert result == {"ok": False, "error": "Orchestrator not initialized"}


async def test_execute_plan_reports_failures(reset_globals):
    """task_1 fails → task_2 (depends on task_1) is marked skipped by planner."""
    async def failing_then_skip(task):
        if task.id == "task_1":
            task.status = "failed"
            task.error = "boom"
        # task_2 should be skipped by the planner BEFORE spawn is called,
        # so we don't need to handle it here.
        return task

    spawner = _make_spawner(spawn_side_effect=failing_then_skip, wait_all_return=[])
    init_orchestrator(spawner, MagicMock())

    plan_json = json.dumps({
        "tasks": [{"goal": "a"}, {"goal": "b"}],
        "dependencies": {"task_2": ["task_1"]},
    })
    result = await execute_plan(plan_json)

    assert result["ok"] is True
    assert result["failed"] == 1  # only task_1 counts as failed
    statuses = {r["status"] for r in result["results"]}
    assert "skipped" in statuses  # task_2 was skipped
    assert "failed" in statuses


# ───────────────────────────── subagent_status ─────────────────────────


async def test_subagent_status_returns_stats(reset_globals):
    stats = {"active": 2, "total": 5, "completed": 2, "failed": 1, "pending": 0}
    spawner = _make_spawner(stats_value=stats)
    init_orchestrator(spawner, MagicMock())

    result = await subagent_status()
    assert result == {"ok": True, "stats": stats}


async def test_subagent_status_not_initialized(reset_globals):
    orchestrator_tools._spawner = None
    result = await subagent_status()
    assert result == {"ok": False, "error": "Orchestrator not initialized"}


# ──────────────────────────── registry wiring ──────────────────────────


def test_runtime_registry_wires_orchestrator_handlers():
    """create_runtime_registry must attach the 4 orchestrator handlers."""
    registry = create_runtime_registry()
    for name in ("spawn_subagent", "collect_results", "execute_plan", "subagent_status"):
        tool = registry.get(name)
        assert tool.handler is not None, f"{name} handler not wired"
        assert callable(tool.handler)


def test_orchestrator_tools_available_in_office_and_coding():
    registry = create_runtime_registry()
    office_names = {t.name for t in registry.list_by_mode("office")}
    coding_names = {t.name for t in registry.list_by_mode("coding")}
    for name in ("spawn_subagent", "collect_results", "execute_plan", "subagent_status"):
        assert name in office_names, f"{name} not available in office mode"
        assert name in coding_names, f"{name} not available in coding mode"


def test_orchestrator_permission_levels():
    registry = create_runtime_registry()
    assert registry.get("spawn_subagent").permission_level == "write"
    assert registry.get("collect_results").permission_level == "read"
    assert registry.get("execute_plan").permission_level == "write"
    assert registry.get("subagent_status").permission_level == "read"
