"""Typed contracts for the agent task control plane.

M7.1.4 adds the immutable CompletionDecision record and its passive,
append-only durable ledger. M7.1.5 adds pure deterministic evaluation of
structured facts. M7.1.8 adds read-only durable continuation recovery;
planning and Recovery/Replan execution remain later control-plane
responsibilities.
"""

from khaos.agent.control.completion import (
    COMPLETION_DECISION_SCHEMA_VERSION,
    AssessmentStatus,
    CompletionDecision,
    CompletionDecisionValidationError,
    CompletionEvidenceKind,
    CompletionEvidenceRef,
    CompletionIssue,
    CompletionIssueCode,
    CompletionOutcome,
    CriterionAssessment,
    EvidenceRef,
    RequirementAssessment,
)
from khaos.agent.control.completion_evaluator import (
    CompletionConstraint,
    CompletionConstraintCode,
    CompletionEvaluationInputError,
    CompletionEvaluationSnapshot,
    CompletionEvaluator,
)
from khaos.agent.control.completion_flow import (
    CompletionDecisionStore,
    CompletionFactBundle,
    CompletionFactProvider,
    CompletionProposal,
    CompletionProposalController,
    CompletionProposalResult,
    CompletionProposalStatus,
    CompletionProposalTrigger,
    CompletionTaskSnapshotReader,
    EmptyCompletionFactProvider,
    GoalSpecLoader,
)
from khaos.agent.control.completion_gate import (
    CompletionAuthorityResult,
    CompletionAuthorityStatus,
    CompletionDecisionReader,
    CompletionGate,
    CompletionGateAuthorityPolicy,
    CompletionGateResult,
    CompletionGateStatus,
    CompletionGoalSpecReader,
    CompletionTaskProjection,
    FailClosedCompletionAuthorityPolicy,
)
from khaos.agent.control.completion_gate_repository import (
    CompletionGateDatabase,
    CompletionGateRepository,
    CompletionProjectionResult,
    CompletionProjectionStatus,
)
from khaos.agent.control.completion_recovery import (
    MAX_COMPLETION_GATE_PAYLOAD_BYTES,
    CompletionContinuationState,
    CompletionGateHistoryEntry,
    CompletionGateHistoryReader,
    CompletionGateHistoryRecord,
    CompletionRecoveryDecisionReader,
    CompletionRecoveryGoalSpecReader,
    CompletionRecoveryResolver,
    CompletionRecoveryService,
    CompletionRecoveryState,
    DatabaseCompletionGateHistoryReader,
)
from khaos.agent.control.completion_repository import (
    CompletionDecisionBindingError,
    CompletionDecisionConflictError,
    CompletionDecisionIntegrityError,
    CompletionDecisionRepository,
    CompletionDecisionRepositoryError,
    StoredCompletionDecision,
)
from khaos.agent.control.goal import (
    ACCEPTANCE_CRITERION_SCHEMA_KEYS,
    GOAL_REQUIREMENT_SCHEMA_KEYS,
    GOAL_SPEC_SCHEMA_VERSION,
    AcceptanceCriterion,
    GoalRequirement,
    GoalSource,
    GoalSpec,
    GoalSpecValidationError,
    normalize_goal,
)
from khaos.agent.control.goal_repository import (
    GoalSpecConflictError,
    GoalSpecIntegrityError,
    GoalSpecRepository,
)
from khaos.agent.control.state import (
    LEGAL_COGNITIVE_TRANSITIONS,
    AgentCognitiveState,
    AgentCognitiveStateMachine,
    CognitiveTransitionValidation,
)
from khaos.agent.control.state_repository import (
    AgentControlStateRepository,
    CognitiveStateIntegrityError,
    CognitiveStateSnapshot,
    CognitiveTransitionResult,
    CognitiveTransitionStatus,
)

__all__ = [
    "ACCEPTANCE_CRITERION_SCHEMA_KEYS",
    "COMPLETION_DECISION_SCHEMA_VERSION",
    "GOAL_REQUIREMENT_SCHEMA_KEYS",
    "GOAL_SPEC_SCHEMA_VERSION",
    "LEGAL_COGNITIVE_TRANSITIONS",
    "MAX_COMPLETION_GATE_PAYLOAD_BYTES",
    "AcceptanceCriterion",
    "AgentCognitiveState",
    "AgentCognitiveStateMachine",
    "AgentControlStateRepository",
    "AssessmentStatus",
    "CognitiveStateIntegrityError",
    "CognitiveStateSnapshot",
    "CognitiveTransitionResult",
    "CognitiveTransitionStatus",
    "CognitiveTransitionValidation",
    "CompletionAuthorityResult",
    "CompletionAuthorityStatus",
    "CompletionConstraint",
    "CompletionConstraintCode",
    "CompletionContinuationState",
    "CompletionDecision",
    "CompletionDecisionBindingError",
    "CompletionDecisionConflictError",
    "CompletionDecisionIntegrityError",
    "CompletionDecisionReader",
    "CompletionDecisionRepository",
    "CompletionDecisionRepositoryError",
    "CompletionDecisionStore",
    "CompletionDecisionValidationError",
    "CompletionEvaluationInputError",
    "CompletionEvaluationSnapshot",
    "CompletionEvaluator",
    "CompletionEvidenceKind",
    "CompletionEvidenceRef",
    "CompletionFactBundle",
    "CompletionFactProvider",
    "CompletionGate",
    "CompletionGateAuthorityPolicy",
    "CompletionGateDatabase",
    "CompletionGateHistoryEntry",
    "CompletionGateHistoryReader",
    "CompletionGateHistoryRecord",
    "CompletionGateRepository",
    "CompletionGateResult",
    "CompletionGateStatus",
    "CompletionGoalSpecReader",
    "CompletionIssue",
    "CompletionIssueCode",
    "CompletionOutcome",
    "CompletionProjectionResult",
    "CompletionProjectionStatus",
    "CompletionProposal",
    "CompletionProposalController",
    "CompletionProposalResult",
    "CompletionProposalStatus",
    "CompletionProposalTrigger",
    "CompletionRecoveryDecisionReader",
    "CompletionRecoveryGoalSpecReader",
    "CompletionRecoveryResolver",
    "CompletionRecoveryService",
    "CompletionRecoveryState",
    "CompletionTaskProjection",
    "CompletionTaskSnapshotReader",
    "CriterionAssessment",
    "DatabaseCompletionGateHistoryReader",
    "EmptyCompletionFactProvider",
    "EvidenceRef",
    "FailClosedCompletionAuthorityPolicy",
    "GoalRequirement",
    "GoalSource",
    "GoalSpec",
    "GoalSpecConflictError",
    "GoalSpecIntegrityError",
    "GoalSpecLoader",
    "GoalSpecRepository",
    "GoalSpecValidationError",
    "RequirementAssessment",
    "StoredCompletionDecision",
    "normalize_goal",
]
