"""Read-only implementation planning contracts and deterministic service."""
from khaos.coding.planning.contracts import *
from khaos.coding.planning.execution_models import (
    ExecutionRunStatus,
    PlanExecutionRun,
    PlannedEditBundle,
    PlannedEditOperation,
    PlannedFileEdit,
    WorkspaceMutationResult,
)
from khaos.coding.planning.repository import (
    PlanningTaskSnapshot,
    PlanPublicationResult,
    PlanPublicationStatus,
    PlanRevisionBindingError,
    PlanRevisionConflictError,
    PlanRevisionIntegrityError,
    PlanRevisionRepository,
    PlanRevisionStaleError,
    StoredPlanRevision,
)
from khaos.coding.planning.revision import (
    PLANNER_ALGORITHM_VERSION,
    PLANNING_SCHEMA_VERSION,
    PlanDisposition,
    PlanningAffectedFile,
    PlanningAffectedSymbol,
    PlanningContractError,
    PlanningDependencyImpact,
    PlanningDiagnostic,
    PlanningEvidenceKind,
    PlanningEvidenceRef,
    PlanningInput,
    PlanningRisk,
    PlanningRiskLevel,
    PlanningStep,
    PlanningVerificationIntent,
    PlanRevision,
    plan_revision_from_canonical_json,
)
from khaos.coding.planning.service import DeterministicPlanningService
from khaos.coding.planning.trusted_verification_authority import (
    FailClosedVerificationEvidenceValidator,
    M4VerificationEvidenceValidator,
    StructuralVerificationEvidenceValidator,
    TrustedVerificationAuthority,
    VerificationAuthorityError,
    VerificationAuthorityInputError,
    VerificationEvidenceValidation,
    VerificationEvidenceValidationStatus,
)
from khaos.coding.planning.trusted_verification_service import (
    TrustedVerificationFactProvider,
    TrustedVerificationPublication,
    TrustedVerificationService,
    TrustedVerificationServiceError,
    TurnVerificationEventSink,
    VerificationEventSink,
    VerificationEventType,
    VerificationObservationEvent,
    build_trusted_verification_input,
    verification_requirements_from_plan,
)
from khaos.coding.planning.verification_assessment import (
    TRUSTED_VERIFICATION_INPUT_SCHEMA_VERSION,
    VERIFICATION_ALGORITHM_VERSION,
    VERIFICATION_ASSESSMENT_SCHEMA_VERSION,
    TrustedVerificationInput,
    VerificationAssessment,
    VerificationAssessmentDisposition,
    VerificationAssessmentStatus,
    VerificationCheckAssessment,
    VerificationContractError,
    VerificationDisposition,
    VerificationEvidence,
    VerificationEvidenceKind,
    VerificationEvidenceRef,
    VerificationExecutionEvidence,
    VerificationExecutionStatus,
    VerificationRequirement,
    VerificationTermination,
)
from khaos.coding.planning.verification_assessment_repository import (
    StoredVerificationAssessment,
    VerificationAssessmentBindingError,
    VerificationAssessmentConflictError,
    VerificationAssessmentIntegrityError,
    VerificationAssessmentRepository,
    VerificationAssessmentRepositoryError,
    VerificationAssessmentUnavailableError,
    VerificationCurrentSnapshot,
    VerificationCurrentSnapshotReader,
    VerificationTaskSnapshot,
)
from khaos.coding.planning.verification_execution_models import (
    TrustedVerificationCommand,
    VerificationExecutionRun,
    VerificationPhaseContext,
    VerificationResult,
    VerificationRunStatus,
    VerificationStepRun,
    VerificationStepStatus,
)


def __getattr__(name: str) -> object:
    """Lazily expose orchestration types without importing workspace code.

    ``khaos.security.resource_scope`` imports planning security identities.
    Eagerly importing the coordinator while that package is initialized would
    recurse through ``coding.workspace`` back into ``resource_scope``.  The
    coordinator remains available through the historical package-level API,
    but is loaded only when a caller explicitly requests an orchestration
    symbol.
    """
    if name in {
        "PlanningControlCoordinator",
        "PlanningControlResult",
        "PlanningControlStatus",
    }:
        from khaos.coding.planning.coordinator import (
            PlanningControlCoordinator,
            PlanningControlResult,
            PlanningControlStatus,
        )

        globals().update(
            {
                "PlanningControlCoordinator": PlanningControlCoordinator,
                "PlanningControlResult": PlanningControlResult,
                "PlanningControlStatus": PlanningControlStatus,
            }
        )
        return globals()[name]
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

__all__ = [
    "PLANNER_ALGORITHM_VERSION",
    "PLANNING_SCHEMA_VERSION",
    "TRUSTED_VERIFICATION_INPUT_SCHEMA_VERSION",
    "VERIFICATION_ALGORITHM_VERSION",
    "VERIFICATION_ASSESSMENT_SCHEMA_VERSION",
    "DeterministicPlanningService",
    "ExecutionRunStatus",
    "FailClosedVerificationEvidenceValidator",
    "M4VerificationEvidenceValidator",
    "PlanDisposition",
    "PlanExecutionRun",
    "PlanPublicationResult",
    "PlanPublicationStatus",
    "PlanRevision",
    "PlanRevisionBindingError",
    "PlanRevisionConflictError",
    "PlanRevisionIntegrityError",
    "PlanRevisionRepository",
    "PlanRevisionStaleError",
    "PlannedEditBundle",
    "PlannedEditOperation",
    "PlannedFileEdit",
    "PlanningAffectedFile",
    "PlanningAffectedSymbol",
    "PlanningContractError",
    "PlanningControlCoordinator",
    "PlanningControlResult",
    "PlanningControlStatus",
    "PlanningDependencyImpact",
    "PlanningDiagnostic",
    "PlanningEvidenceKind",
    "PlanningEvidenceRef",
    "PlanningInput",
    "PlanningRisk",
    "PlanningRiskLevel",
    "PlanningStep",
    "PlanningTaskSnapshot",
    "PlanningVerificationIntent",
    "StoredPlanRevision",
    "StoredVerificationAssessment",
    "StructuralVerificationEvidenceValidator",
    "TrustedVerificationAuthority",
    "TrustedVerificationCommand",
    "TrustedVerificationFactProvider",
    "TrustedVerificationInput",
    "TrustedVerificationPublication",
    "TrustedVerificationService",
    "TrustedVerificationServiceError",
    "TurnVerificationEventSink",
    "VerificationAssessment",
    "VerificationAssessmentBindingError",
    "VerificationAssessmentConflictError",
    "VerificationAssessmentDisposition",
    "VerificationAssessmentIntegrityError",
    "VerificationAssessmentRepository",
    "VerificationAssessmentRepositoryError",
    "VerificationAssessmentStatus",
    "VerificationAssessmentUnavailableError",
    "VerificationAuthorityError",
    "VerificationAuthorityInputError",
    "VerificationCheckAssessment",
    "VerificationContractError",
    "VerificationCurrentSnapshot",
    "VerificationCurrentSnapshotReader",
    "VerificationDisposition",
    "VerificationEventSink",
    "VerificationEventType",
    "VerificationEvidence",
    "VerificationEvidenceKind",
    "VerificationEvidenceRef",
    "VerificationEvidenceValidation",
    "VerificationEvidenceValidationStatus",
    "VerificationExecutionEvidence",
    "VerificationExecutionRun",
    "VerificationExecutionStatus",
    "VerificationObservationEvent",
    "VerificationPhaseContext",
    "VerificationRequirement",
    "VerificationResult",
    "VerificationRunStatus",
    "VerificationStepRun",
    "VerificationStepStatus",
    "VerificationTaskSnapshot",
    "VerificationTermination",
    "WorkspaceMutationResult",
    "build_trusted_verification_input",
    "plan_revision_from_canonical_json",
    "verification_requirements_from_plan",
]
